/**
 * Terrain invariants.
 *
 * The map is generated by ~250 lines of imperative painting, so it is easy for
 * a later edit to leave the visuals and the collision disagreeing — a tile that
 * looks like dry ground but blocks movement, or looks like water but does not.
 * The pond shipped that way: blocked water painted in SHOAL's old tan sand.
 */
const w = await import("../world.ts");

let fail = 0;
const ok = (c: boolean, m: string) => {
  console.log((c ? "  PASS  " : "  FAIL  ") + m);
  if (!c) fail++;
};

// Every declared kind is actually used; every painted kind is declared.
const used = new Set<number>();
for (let i = 0; i < w.kinds.length; i++) used.add(w.kinds[i]);
const declared = new Set<number>(Object.values(w.KIND) as number[]);
const orphanKinds = [...declared].filter((k) => !used.has(k));
const undeclared = [...used].filter((k) => !declared.has(k));
ok(orphanKinds.length === 0, `no declared-but-unpainted kinds (${orphanKinds})`);
ok(undeclared.length === 0, `no painted-but-undeclared kinds (${undeclared})`);
ok([...used].every((k) => w.KIND_COLORS[k] !== undefined), "every painted kind has a colour");

// SHOAL means standing water: it must be blocked and it must sit low enough
// that Terrain.tsx applies the water tint.
let shoalDry = 0;
let shoalHigh = 0;
for (let j = 0; j < 96; j++) {
  for (let i = 0; i < 96; i++) {
    const n = j * 96 + i;
    if (w.kinds[n] !== w.KIND.SHOAL) continue;
    if (!w.blocked[n]) shoalDry++;
    if (w.heights[n] > w.WATER_LEVEL) shoalHigh++;
  }
}
ok(shoalDry === 0, `all water tiles are blocked (${shoalDry} walkable)`);
ok(shoalHigh === 0, `all water tiles render as water (${shoalHigh} above WATER_LEVEL)`);

// The inverse: nothing at or below WATER_LEVEL should be walkable, or the
// player would appear to stroll across a pond.
let lowWalkable = 0;
for (let n = 0; n < w.kinds.length; n++) {
  if (w.heights[n] <= w.WATER_LEVEL && !w.blocked[n]) lowWalkable++;
}
ok(lowWalkable === 0, `nothing submerged is walkable (${lowWalkable})`);

console.log(fail ? `\n${fail} TERRAIN FAILURE(S)` : "\nTERRAIN OK");
process.exit(fail ? 1 : 0);
